import { JeeQuestion } from "./jeeData";

export const PHYSICS_PYQS: JeeQuestion[] = [
  // =========================================================================
  // 1. UNITS & MEASUREMENTS
  // =========================================================================
  {
    id: "phy-uam-2026-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Analysis",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 24, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "The physical quantity having the same dimensions as that of Planck's constant (h) divided by 2π is:",
    options: [
      { id: "A", text: "Linear Momentum" },
      { id: "B", text: "Angular Momentum" },
      { id: "C", text: "Work Done" },
      { id: "D", text: "Energy Density" },
    ],
    correctOption: "B",
    solution: "Planck's constant h has dimensions [M L² T⁻¹].\nAngular momentum L = r × p = [L][M L T⁻¹] = [M L² T⁻¹].\nThus, h/(2π) has the exact dimensions of Angular Momentum.",
  },
  {
    id: "phy-uam-2025-s2",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Errors in Measurement",
    exam: "JEE Main",
    year: 2025,
    examDate: "Jan 29, 2025",
    session: "January",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A physical quantity Z is given by Z = (A² B^(1/3)) / (C³ D^(1/2)). The percentage error in measurement of A, B, C and D are 1%, 3%, 2% and 4% respectively. The relative percentage error in Z is:",
    options: [
      { id: "A", text: "11%" },
      { id: "B", text: "9%" },
      { id: "C", text: "12%" },
      { id: "D", text: "14%" },
    ],
    correctOption: "A",
    solution: "Percentage error in Z = 2(ΔA/A) + (1/3)(ΔB/B) + 3(ΔC/C) + (1/2)(ΔD/D)\n= 2(1%) + (1/3)(3%) + 3(2%) + (1/2)(4%)\n= 2% + 1% + 6% + 2% = 11%.",
  },
  {
    id: "phy-uam-2024-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Significant Figures & Rounding",
    exam: "JEE Main",
    year: 2024,
    examDate: "Jan 30, 2024",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "If speed of light C, gravitational constant G, and Planck's constant h are chosen as fundamental quantities, the dimension of time in terms of C, G, and h is:",
    options: [
      { id: "A", text: "G^(1/2) h^(1/2) C^(-5/2)" },
      { id: "B", text: "G^(1/2) h^(1/2) C^(-3/2)" },
      { id: "C", text: "G^(1/2) h^(-1/2) C^(-5/2)" },
      { id: "D", text: "G^(-1/2) h^(1/2) C^(3/2)" },
    ],
    correctOption: "A",
    solution: "Let t ∝ G^a h^b C^c.\n[T] = [M⁻¹ L³ T⁻²]^a [M L² T⁻¹]^b [L T⁻¹]^c\nComparing powers of M, L, T:\n-a + b = 0 ⇒ a = b = 1/2.\n3a + 2b + c = 0 ⇒ 3(1/2) + 2(1/2) + c = 0 ⇒ c = -5/2.\nHence t = G^(1/2) h^(1/2) C^(-5/2).",
  },
  {
    id: "phy-uam-2023-s2",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Analysis",
    exam: "JEE Main",
    year: 2023,
    examDate: "Apr 11, 2023",
    session: "April",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "The dimension of magnetic permeability μ₀ is expressed as:",
    options: [
      { id: "A", text: "[M L T⁻² A⁻²]" },
      { id: "B", text: "[M L T⁻¹ A⁻²]" },
      { id: "C", text: "[M L² T⁻² A⁻¹]" },
      { id: "D", text: "[M L T⁻² A⁻¹]" },
    ],
    correctOption: "A",
    solution: "Force per unit length between parallel wires: F/L = (μ₀ I₁ I₂) / (2π r).\n[μ₀] = [F] [r] / ([L] [I²]) = ([M L T⁻²] [L]) / ([L] [A²]) = [M L T⁻² A⁻²].",
  },
  {
    id: "phy-uam-2022-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Errors in Measurement",
    exam: "JEE Main",
    year: 2022,
    examDate: "Jul 25, 2022",
    session: "July",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "The density of a cube is measured by measuring its mass and the length of its sides. If maximum errors in mass and length are 3% and 2% respectively, the maximum error in density is:",
    options: [
      { id: "A", text: "9%" },
      { id: "B", text: "7%" },
      { id: "C", text: "5%" },
      { id: "D", text: "1%" },
    ],
    correctOption: "A",
    solution: "Density ρ = m / L³.\nΔρ/ρ = Δm/m + 3(ΔL/L) = 3% + 3(2%) = 3% + 6% = 9%.",
  },
  {
    id: "phy-uam-2021-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Formulae",
    exam: "JEE Main",
    year: 2021,
    examDate: "Feb 24, 2021",
    session: "February",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "Match List-I with List-II:\n(P) Torque -> (1) [M L² T⁻²]\n(Q) Stress -> (2) [M L⁻¹ T⁻²]\n(R) Latent Heat -> (3) [L² T⁻²]\n(S) Power -> (4) [M L² T⁻³]",
    options: [
      { id: "A", text: "P-1, Q-2, R-3, S-4" },
      { id: "B", text: "P-2, Q-1, R-3, S-4" },
      { id: "C", text: "P-1, Q-2, R-4, S-3" },
      { id: "D", text: "P-4, Q-3, R-2, S-1" },
    ],
    correctOption: "A",
    solution: "Torque = r × F = [M L² T⁻²]\nStress = F / A = [M L⁻¹ T⁻²]\nLatent Heat = Q / m = [L² T⁻²]\nPower = W / t = [M L² T⁻³].",
  },
  {
    id: "phy-uam-2020-s2",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Analysis",
    exam: "JEE Main",
    year: 2020,
    examDate: "Jan 07, 2020",
    session: "January",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "The quantity X = ε₀ L (ΔV / Δt), where ε₀ is permittivity, L is length, ΔV is potential difference, and Δt is time interval. The dimensional formula of X is the same as that of:",
    options: [
      { id: "A", text: "Electric Current" },
      { id: "B", text: "Resistance" },
      { id: "C", text: "Electric Charge" },
      { id: "D", text: "Voltage" },
    ],
    correctOption: "A",
    solution: "Capacitance C ≈ ε₀ L.\nThen X = C (ΔV / Δt) = ΔQ / Δt = Electric Current I.\nThus, X has dimensions of Electric Current [A].",
  },
  {
    id: "phy-uam-2019-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Formulae",
    exam: "JEE Main",
    year: 2019,
    examDate: "Jan 09, 2019",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "The force F is given in terms of time t and distance x by F = A sin(C t) + B cos(D x). Then the dimensions of A/B and C/D are respectively:",
    options: [
      { id: "A", text: "[M⁰ L⁰ T⁰] and [L T⁻¹]" },
      { id: "B", text: "[M L T⁻²] and [L⁻¹ T]" },
      { id: "C", text: "[M⁰ L⁰ T⁰] and [L⁻¹ T⁻¹]" },
      { id: "D", text: "[M⁰ L T⁻¹] and [L T]" },
    ],
    correctOption: "A",
    solution: "F = A sin(Ct) + B cos(Dx).\nSince F, A, and B must have the same unit of Force: [A] = [B] = [M L T⁻²] ⇒ [A/B] = [M⁰ L⁰ T⁰].\nArgument of sin and cos are dimensionless: [C t] = 1 ⇒ [C] = [T⁻¹]; [D x] = 1 ⇒ [D] = [L⁻¹].\n[C/D] = [T⁻¹] / [L⁻¹] = [L T⁻¹].",
  },
  {
    id: "phy-uam-2018-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Significant Figures",
    exam: "JEE Main",
    year: 2018,
    examDate: "Apr 15, 2018",
    session: "April",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "A student measures the length of a rod as 3.50 cm using a vernier caliper. The number of significant figures in this measurement is:",
    options: [
      { id: "A", text: "3" },
      { id: "B", text: "2" },
      { id: "C", text: "4" },
      { id: "D", text: "1" },
    ],
    correctOption: "A",
    solution: "Trailing zeros after a decimal point in a measured quantity are significant. Hence '3.50' has 3 significant figures.",
  },
  {
    id: "phy-uam-2016-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Analysis",
    exam: "JEE Main",
    year: 2016,
    examDate: "Apr 03, 2016",
    session: "April",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "A, B, C, D are physical quantities having different dimensions. None of them can be zero. Which of the following expressions can never be meaningful?",
    options: [
      { id: "A", text: "(A - B) / C" },
      { id: "B", text: "A B - C D" },
      { id: "C", text: "(A B) / D" },
      { id: "D", text: "(A + B) / C" },
    ],
    correctOption: "A",
    solution: "Quantities with different dimensions can NEVER be added or subtracted. Since A and B have different dimensions, (A - B) is physically invalid.",
  },
  {
    id: "phy-uam-2015-s1",
    subject: "Physics",
    chapter: "Units & Measurements",
    subtopic: "Dimensional Analysis",
    exam: "JEE Main",
    year: 2015,
    examDate: "Apr 04, 2015",
    session: "April",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Hard",
    question: "If electronic charge e, electron mass m, speed of light c, and Planck's constant h are fundamental constants, the dimension of permeability μ₀ can be expressed as:",
    options: [
      { id: "A", text: "h c / e²" },
      { id: "B", text: "h e² / c" },
      { id: "C", text: "e² / (h c)" },
      { id: "D", text: "m c / e²" },
    ],
    correctOption: "A",
    solution: "Fine structure constant α = e² / (4π ε₀ ħ c) is dimensionless.\nSince c = 1 / √(ε₀ μ₀), we get μ₀ c = 1 / (ε₀ c) ∝ h / e².\nThus μ₀ ∝ h c / e².",
  },

  // =========================================================================
  // 2. KINEMATICS
  // =========================================================================
  {
    id: "phy-kin-2026-s1",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Projectile Motion",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 27, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A ball is projected from ground level with speed 40 m/s at angle 60° to horizontal. The time after projection when its velocity vector makes an angle of 45° with the horizontal during ascent is (g = 10 m/s²):",
    options: [
      { id: "A", text: "2(√3 - 1) s" },
      { id: "B", text: "(2√3 - 1) s" },
      { id: "C", text: "4(√3 - 1) s" },
      { id: "D", text: "2(√3 + 1) s" },
    ],
    correctOption: "A",
    solution: "Initial velocity components: u_x = 40 cos 60° = 20 m/s, u_y = 40 sin 60° = 20√3 m/s.\nAt angle 45°: tan 45° = v_y / v_x = 1 ⇒ v_y = v_x = 20 m/s.\nv_y = u_y - g t ⇒ 20 = 20√3 - 10 t ⇒ 10 t = 20(√3 - 1) ⇒ t = 2(√3 - 1) s.",
  },
  {
    id: "phy-kin-2026-s2",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Motion in 1D & Graphs",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 27, 2026",
    session: "January",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "The displacement x of a particle moving along a straight line varies with time t as x = t³ - 6t² + 9t + 2 (where x is in meters and t in seconds). The acceleration of the particle when it comes to rest is:",
    options: [
      { id: "A", text: "6 m/s²" },
      { id: "B", text: "-6 m/s²" },
      { id: "C", text: "±6 m/s²" },
      { id: "D", text: "12 m/s²" },
    ],
    correctOption: "C",
    solution: "Velocity v = dx/dt = 3t² - 12t + 9.\nParticle comes to rest when v = 0 ⇒ 3(t - 1)(t - 3) = 0 ⇒ t = 1 s or t = 3 s.\nAcceleration a = dv/dt = 6t - 12.\nAt t = 1 s: a = 6(1) - 12 = -6 m/s².\nAt t = 3 s: a = 6(3) - 12 = +6 m/s².\nHence acceleration is ±6 m/s².",
  },
  {
    id: "phy-kin-2025-s1",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Relative Motion in 2D",
    exam: "JEE Main",
    year: 2025,
    examDate: "Jan 23, 2025",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Hard",
    question: "A swimmer can swim with a speed of 4 km/h in still water. He wants to cross a 1 km wide river flowing with a speed of 3 km/h along the shortest path. The time taken to cross the river is:",
    options: [
      { id: "A", text: "1 / √7 h" },
      { id: "B", text: "1 / 5 h" },
      { id: "C", text: "1 / 4 h" },
      { id: "D", text: "2 / √7 h" },
    ],
    correctOption: "A",
    solution: "Shortest path means net motion is straight across perpendicular to river flow.\nNet velocity perpendicular to bank v_net = √(v_s² - v_r²) = √(4² - 3²) = √7 km/h.\nTime t = width / v_net = 1 / √7 h.",
  },
  {
    id: "phy-kin-2024-s1",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Projectile Motion",
    exam: "JEE Main",
    year: 2024,
    examDate: "Jan 27, 2024",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A particle is projected with velocity u at angle θ to horizontal. The ratio of its kinetic energy at maximum height to its initial kinetic energy is 1/4. The angle of projection θ is:",
    options: [
      { id: "A", text: "60°" },
      { id: "B", text: "45°" },
      { id: "C", text: "30°" },
      { id: "D", text: "75°" },
    ],
    correctOption: "A",
    solution: "Initial KE = 1/2 m u².\nVelocity at max height = u cos θ.\nKE at max height = 1/2 m (u cos θ)² = (1/2 m u²) cos² θ.\nGiven KE_top / KE_initial = cos² θ = 1/4 ⇒ cos θ = 1/2 ⇒ θ = 60°.",
  },
  {
    id: "phy-kin-2023-s1",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Calculus in Kinematics",
    exam: "JEE Main",
    year: 2023,
    examDate: "Jan 24, 2023",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "The position of a particle varies as x = (2t² - 4t + 5) m. The average velocity of the particle between t = 0 and t = 3 s is:",
    options: [
      { id: "A", text: "2 m/s" },
      { id: "B", text: "4 m/s" },
      { id: "C", text: "6 m/s" },
      { id: "D", text: "3 m/s" },
    ],
    correctOption: "A",
    solution: "At t = 0: x(0) = 5 m.\nAt t = 3: x(3) = 2(3)² - 4(3) + 5 = 18 - 12 + 5 = 11 m.\nAverage velocity = (x(3) - x(0)) / (3 - 0) = (11 - 5) / 3 = 6 / 3 = 2 m/s.",
  },
  {
    id: "phy-kin-2022-s2",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Motion under Gravity",
    exam: "JEE Main",
    year: 2022,
    examDate: "Jun 26, 2022",
    session: "June",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A stone dropped from the top of a tower travels 5/9 of the total height in the last second of its fall. The height of the tower is (g = 10 m/s²):",
    options: [
      { id: "A", text: "45 m" },
      { id: "B", text: "80 m" },
      { id: "C", text: "125 m" },
      { id: "D", text: "100 m" },
    ],
    correctOption: "A",
    solution: "Total height H = 1/2 g t².\nHeight covered in (t - 1) seconds H' = 1/2 g (t - 1)².\nDistance in last second S_nth = H - H' = 5/9 H ⇒ H' = 4/9 H.\n(t - 1)² / t² = 4/9 ⇒ (t - 1) / t = 2/3 ⇒ 3t - 3 = 2t ⇒ t = 3 s.\nH = 1/2 (10) (3)² = 45 m.",
  },
  {
    id: "phy-kin-2021-s1",
    subject: "Physics",
    chapter: "Kinematics",
    subtopic: "Relative Motion",
    exam: "JEE Main",
    year: 2021,
    examDate: "Mar 16, 2021",
    session: "March",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "Two cars A and B are moving in the same direction with velocities 30 m/s and 20 m/s respectively. Car A is 100 m behind B. The time taken by car A to catch car B is:",
    options: [
      { id: "A", text: "10 s" },
      { id: "B", text: "20 s" },
      { id: "C", text: "5 s" },
      { id: "D", text: "15 s" },
    ],
    correctOption: "A",
    solution: "Relative velocity v_rel = v_A - v_B = 30 - 20 = 10 m/s.\nRelative distance d = 100 m.\nTime t = d / v_rel = 100 / 10 = 10 s.",
  },

  // =========================================================================
  // 3. LAWS OF MOTION
  // =========================================================================
  {
    id: "phy-lom-2026-s1",
    subject: "Physics",
    chapter: "Laws of Motion",
    subtopic: "Friction & Inclined Planes",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 28, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A body of mass 5 kg is placed on an inclined plane of inclination 30°. The coefficient of friction between the body and incline is μ = 1/(2√3). The minimum force applied parallel to the incline to move the body UP the incline is (g = 10 m/s²):",
    options: [
      { id: "A", text: "37.5 N" },
      { id: "B", text: "25 N" },
      { id: "C", text: "12.5 N" },
      { id: "D", text: "50 N" },
    ],
    correctOption: "A",
    solution: "Force required to pull body up: F = m g sin θ + f_k = m g sin θ + μ m g cos θ.\nF = 5 * 10 * sin 30° + (1 / (2√3)) * 5 * 10 * cos 30°\n= 25 + (1 / (2√3)) * 50 * (√3 / 2) = 25 + 12.5 = 37.5 N.",
  },
  {
    id: "phy-lom-2025-s1",
    subject: "Physics",
    chapter: "Laws of Motion",
    subtopic: "Circular Motion & Banking",
    exam: "JEE Main",
    year: 2025,
    examDate: "Jan 24, 2025",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "A curved road of radius 50 m is banked for a speed of 36 km/h. The banking angle θ of the road is (g = 10 m/s²):",
    options: [
      { id: "A", text: "tan⁻¹(0.2)" },
      { id: "B", text: "tan⁻¹(0.1)" },
      { id: "C", text: "tan⁻¹(0.5)" },
      { id: "D", text: "tan⁻¹(0.4)" },
    ],
    correctOption: "A",
    solution: "v = 36 km/h = 36 * (5/18) = 10 m/s.\nFormula for banking angle: tan θ = v² / (r g).\ntan θ = (10)² / (50 * 10) = 100 / 500 = 0.2 ⇒ θ = tan⁻¹(0.2).",
  },
  {
    id: "phy-lom-2024-s2",
    subject: "Physics",
    chapter: "Laws of Motion",
    subtopic: "Pulleys & Tension Analysis",
    exam: "JEE Main",
    year: 2024,
    examDate: "Jan 31, 2024",
    session: "January",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "Two masses m₁ = 4 kg and m₂ = 6 kg are connected by a string passing over a frictionless light pulley. The tension in the string during motion is (g = 10 m/s²):",
    options: [
      { id: "A", text: "48 N" },
      { id: "B", text: "24 N" },
      { id: "C", text: "60 N" },
      { id: "D", text: "36 N" },
    ],
    correctOption: "A",
    solution: "Tension in Atwood machine: T = (2 m₁ m₂ / (m₁ + m₂)) g.\nT = (2 * 4 * 6 / (4 + 6)) * 10 = (48 / 10) * 10 = 48 N.",
  },

  // =========================================================================
  // 4. WORK, ENERGY & POWER
  // =========================================================================
  {
    id: "phy-wep-2026-s1",
    subject: "Physics",
    chapter: "Work, Energy & Power",
    subtopic: "Work-Energy Theorem",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 29, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A force F = (3x² + 2x - 7) N acts on a 2 kg mass displacing it from x = 0 to x = 2 m. The work done by the force is:",
    options: [
      { id: "A", text: "-2 J" },
      { id: "B", text: "2 J" },
      { id: "C", text: "12 J" },
      { id: "D", text: "8 J" },
    ],
    correctOption: "A",
    solution: "W = ∫ F dx from 0 to 2 = ∫ (3x² + 2x - 7) dx = [x³ + x² - 7x]₀²\n= (2³ + 2² - 7(2)) - 0 = 8 + 4 - 14 = -2 J.",
  },
  {
    id: "phy-wep-2025-s2",
    subject: "Physics",
    chapter: "Work, Energy & Power",
    subtopic: "Collisions in 1D",
    exam: "JEE Main",
    year: 2025,
    examDate: "Jan 28, 2025",
    session: "January",
    shift: "Shift 2",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "A mass m moving with speed v collides head-on elastically with a stationary mass 3m. The fractional loss of kinetic energy of the moving mass m is:",
    options: [
      { id: "A", text: "3 / 4" },
      { id: "B", text: "1 / 4" },
      { id: "C", text: "1 / 2" },
      { id: "D", text: "3 / 16" },
    ],
    correctOption: "A",
    solution: "Final velocity of mass m: v₁ = ((m - 3m)/(m + 3m)) v = (-2m / 4m) v = -v/2.\nFinal KE of mass m = 1/2 m (-v/2)² = 1/4 (1/2 m v²) = 1/4 KE_i.\nFractional energy lost by mass m = (KE_i - 1/4 KE_i) / KE_i = 3/4.",
  },

  // =========================================================================
  // 5. ROTATIONAL MOTION
  // =========================================================================
  {
    id: "phy-rot-2026-s1",
    subject: "Physics",
    chapter: "Rotational Motion",
    subtopic: "Moment of Inertia Theorems",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 30, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "The moment of inertia of a uniform solid sphere of mass M and radius R about a tangent is:",
    options: [
      { id: "A", text: "(7 / 5) M R²" },
      { id: "B", text: "(2 / 5) M R²" },
      { id: "C", text: "(3 / 5) M R²" },
      { id: "D", text: "(7 / 3) M R²" },
    ],
    correctOption: "A",
    solution: "By Parallel Axis Theorem: I_tangent = I_cm + M R² = (2/5) M R² + M R² = (7/5) M R².",
  },

  // =========================================================================
  // 6. GRAVITATION
  // =========================================================================
  {
    id: "phy-grv-2026-s1",
    subject: "Physics",
    chapter: "Gravitation",
    subtopic: "Escape Velocity & Satellite Speed",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 31, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "If radius of Earth shrinks by 1% while its mass remains constant, the percentage change in acceleration due to gravity on Earth's surface is:",
    options: [
      { id: "A", text: "Increases by 2%" },
      { id: "B", text: "Decreases by 2%" },
      { id: "C", text: "Increases by 1%" },
      { id: "D", text: "Decreases by 1%" },
    ],
    correctOption: "A",
    solution: "g = G M / R².\nΔg / g = -2 (ΔR / R) = -2 (-1%) = +2%.\nThus, g increases by 2%.",
  },

  // =========================================================================
  // 7. THERMODYNAMICS & KTG
  // =========================================================================
  {
    id: "phy-thm-2026-s1",
    subject: "Physics",
    chapter: "Thermodynamics",
    subtopic: "Isothermal & Adiabatic Processes",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 25, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "An ideal gas at pressure P₀ and volume V₀ is compressed adiabatically to one-eighth of its volume. If γ = 5/3, the final pressure of the gas is:",
    options: [
      { id: "A", text: "32 P₀" },
      { id: "B", text: "16 P₀" },
      { id: "C", text: "8 P₀" },
      { id: "D", text: "64 P₀" },
    ],
    correctOption: "A",
    solution: "For adiabatic process: P₁ V₁^γ = P₂ V₂^γ.\nP₀ V₀^(5/3) = P₂ (V₀ / 8)^(5/3) ⇒ P₂ = P₀ (8)^(5/3) = P₀ (2³)^(5/3) = P₀ (2⁵) = 32 P₀.",
  },

  // =========================================================================
  // 8. ELECTROSTATICS & CAPACITANCE
  // =========================================================================
  {
    id: "phy-ele-2026-s1",
    subject: "Physics",
    chapter: "Electrostatics",
    subtopic: "Electric Field & Dipole",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 27, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Medium",
    question: "Two point charges +q and -4q are fixed at a distance 'a' apart. The location of the point on the line joining them where net electric field is zero is:",
    options: [
      { id: "A", text: "At distance 'a' from +q on the side opposite to -4q" },
      { id: "B", text: "At distance 'a/3' from +q between charges" },
      { id: "C", text: "At distance '2a' from -4q between charges" },
      { id: "D", text: "At distance 'a/2' from +q on the side opposite to -4q" },
    ],
    correctOption: "A",
    solution: "Null point must lie outside the charges on the side of smaller magnitude charge (+q).\nLet distance from +q be x.\nk q / x² = k (4q) / (a + x)² ⇒ 1 / x = 2 / (a + x) ⇒ a + x = 2x ⇒ x = a.\nHence at distance 'a' from +q on the side opposite to -4q.",
  },

  // =========================================================================
  // 9. CURRENT ELECTRICITY
  // =========================================================================
  {
    id: "phy-cur-2026-s1",
    subject: "Physics",
    chapter: "Current Electricity",
    subtopic: "Kirchhoff Laws & Wheatstone Bridge",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 28, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "In a meter bridge experiment, null point is obtained at 40 cm from left end when unknown resistance X is in left gap and 15 Ω is in right gap. The value of X is:",
    options: [
      { id: "A", text: "10 Ω" },
      { id: "B", text: "22.5 Ω" },
      { id: "C", text: "15 Ω" },
      { id: "D", text: "12 Ω" },
    ],
    correctOption: "A",
    solution: "Balanced Wheatstone condition: X / R = l / (100 - l).\nX / 15 = 40 / 60 = 2 / 3 ⇒ X = 15 * (2/3) = 10 Ω.",
  },

  // =========================================================================
  // 10. RAY OPTICS
  // =========================================================================
  {
    id: "phy-opt-2026-s1",
    subject: "Physics",
    chapter: "Ray Optics",
    subtopic: "Refraction through Prism",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 30, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "A ray of light is incident at angle 60° on one face of a prism of refracting angle A = 60°. If ray suffers minimum deviation, refractive index of prism material is:",
    options: [
      { id: "A", text: "√3" },
      { id: "B", text: "√2" },
      { id: "C", text: "1.5" },
      { id: "D", text: "4 / 3" },
    ],
    correctOption: "A",
    solution: "At minimum deviation i₁ = i₂ = 60° and r = A / 2 = 30°.\nμ = sin i / sin r = sin 60° / sin 30° = (√3 / 2) / (1 / 2) = √3.",
  },

  // =========================================================================
  // 11. SEMICONDUCTORS
  // =========================================================================
  {
    id: "phy-sem-2026-s1",
    subject: "Physics",
    chapter: "Semiconductor Electronics",
    subtopic: "Logic Gates",
    exam: "JEE Main",
    year: 2026,
    examDate: "Jan 31, 2026",
    session: "January",
    shift: "Shift 1",
    questionType: "MCQ",
    difficulty: "Easy",
    question: "The Boolean expression for the output Y of a circuit formed by connecting two NOR gates in cascade followed by an AND gate with inputs A and B is equivalent to:",
    options: [
      { id: "A", text: "A AND B" },
      { id: "B", text: "A OR B" },
      { id: "C", text: "NAND" },
      { id: "D", text: "XOR" },
    ],
    correctOption: "A",
    solution: "Inputs inverted via NOR buffers give A' and B'. Passing A' and B' into NOR gate gives (A' + B')' = A'' . B'' = A AND B (De Morgan's theorem).",
  },
];
